name: Tests and release
on:
  push:
    branches:
      - master
      - beta
      - v5
  pull_request:
    branches:
      - master
      - beta
      - v5
jobs:
  workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run build:prod
      - name: Linting
        run: |
          npm run lint
      - name: Unit tests
        run: |
          npm run test:ci
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Deploy sample app to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
          STREAM_API_KEY: ${{ vars.STREAM_DEMO_API_KEY }}
          STREAM_TOKEN_URL: ${{ vars.STREAM_DEMO_TOKEN_URL }}
          STREAM_USER_ID: <dynamic user>
          STREAM_CHANNELS_FILTER: '{"type": "messaging"}'
        run: >
          yarn vercel pull --yes --environment=${{ github.ref == 'refs/heads/v5' && 'production' || 'preview' }} --token=${{ secrets.VERCEL_TOKEN }} &&
          yarn vercel build ${{ github.ref == 'refs/heads/v5' && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }} &&
          yarn vercel deploy ${{ github.ref == 'refs/heads/v5' && '--prod' || '' }} --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      - name: Copy docs from stream-chat-css
        run: npm run ${{ (github.ref == 'refs/heads/v5' || contains(github.head_ref, 'v5')) && 'copy-css-docs:v5' || 'copy-css-docs' }}
      - name: Generate docs
        run: |
          npm run ${{ (github.ref == 'refs/heads/v5' || contains(github.head_ref, 'v5')) && 'generate-docs:v5' || 'generate-docs' }}
      - name: Push to docusaurus
        uses: GetStream/push-stream-chat-docusaurus-action@main
        with:
          target-branch: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/v5') && 'production' || 'staging' }}
        env:
          DOCUSAURUS_GH_TOKEN: ${{ secrets.DOCUSAURUS_GH_TOKEN }}
